### ISSUE TITLE
Schematics

### ISSUE THREAD

**Issue by qiapz** [dimonmontana/LMT01-sensor-library#2]
Hi man,

I am trying to read an smd LMT01 these days and somehow I couldn't manage to make arduino to count the pulses.

While I was searching the internet, I saw your repository and wanted to try but the link of the schematic is broken.

If you can upload a new schematic or repair the old link, I'd be appriciated.

Best.

**Comment by dimonmontana** [comment]
Hey, 
Thanks for the information about the broken link. Now it's restored again!

**Comment by qiapz** [comment]
Thanks. I will try it as soon as possible with the given schematic.
